# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EvaluateDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QInputDialog, QWidget, QListWidget, QDialog

Cricket = sqlite3.connect("Cricket_Players_Database.db")

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        icon_1 = QtGui.QIcon()
        icon_1.addPixmap(QtGui.QPixmap("Images/manage.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon_1)
        Dialog.resize(800, 800)
        Dialog.setAutoFillBackground(False)
        Dialog.setModal(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem_1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem_1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_3.addWidget(self.comboBox_2)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setStyleSheet("color: rgb(0, 85, 255);")
        self.listWidget_2.setObjectName("listWidget_2")
        self.horizontalLayout.addWidget(self.listWidget_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(0, 85, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setEnabled(False)
        self.lineEdit.setFrame(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(2)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: black;\n"
"color: white;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: bold 30px;\n"
"padding: 6px;\n"
"min-width: 10px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setStyleSheet("background-color: white;\n"
"color: red;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"font: bold 25px;\n"
"padding: 6px;\n"
"min-width: 10px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem12)

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(self.reset)
        self.pushButton_2.clicked.connect(self.reset)
        self.pushButton_2.clicked.connect(self.listWidget.clear)
        self.pushButton_2.clicked.connect(self.listWidget_2.clear)
        self.pushButton_2.clicked.connect(self.lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        c = Cricket.cursor()
        Saved_Teams = "SELECT Name FROM Teams;"
        c.execute(Saved_Teams)
        f = c.fetchall()
        items = ["---Select a Team---"]
        for i in f:
            items.append(i[0])
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItems(items)
        index = self.comboBox_2.findText("---Select a Team---", QtCore.Qt.MatchFixedString)
        self.comboBox_2.setCurrentIndex(index)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        index1 = self.comboBox.findText("---Select a Match---", QtCore.Qt.MatchFixedString)
        self.comboBox.setCurrentIndex(index1)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(["---Select a Match---","Match1","Match2","Match3","Match4","Match5"])

        self.pushButton.clicked.connect(self.CalculateScore)

    def reset(self):
        index = self.comboBox_2.findText("---Select a Team---", QtCore.Qt.MatchFixedString)
        self.comboBox_2.setCurrentIndex(index)
        index1 = self.comboBox.findText("---Select a Match---", QtCore.Qt.MatchFixedString)
        self.comboBox.setCurrentIndex(index1)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Evaluate Teams"))
        self.label.setText(_translate("Dialog", "Evaluate the Performance of your Fantasy Team"))
        self.label_3.setText(_translate("Dialog", "Players: "))
        self.label_2.setText(_translate("Dialog", "Points: "))
        self.label_4.setText(_translate("Dialog", "Your Team Points: "))
        self.pushButton.setText(_translate("Dialog", "Calculate Score"))
        self.pushButton_2.setText(_translate("Dialog", "Reset"))

    def CalculateScore(self):
        if self.comboBox_2.currentText() != "---Select a Team---" and self.comboBox.currentText() != "---Select a Match---":
            self.listWidget.clear()
            self.listWidget_2.clear()
            self.lineEdit.setText("")
            c = Cricket.cursor()
            team = self.comboBox_2.currentText()
            mat = self.comboBox.currentText()
            player_team = "SELECT * from Teams WHERE Name = '"+team+"';"
            c.execute(player_team)
            members = c.fetchall()
            players_list = members[0][1].split(",")
            _list = []
            for i in players_list:
                self.listWidget.addItem(i)
                d = {}
                match = self.MatchTables(mat,i)
                player_stat = "SELECT * from Stats WHERE Player = '"+i+"';"
                c.execute(player_stat)
                stats = c.fetchall()
                d["name"] = match[0][0]
                d["role"] = stats[0][6]
                d["runs"] = match[0][1]
                d["4"] =  match[0][3]
                d["6"] = match[0][4]
                d["balls"] = match[0][2]
                d["field"] = match[0][9]+match[0][10]+match[0][11]
                d["wkts"] = match[0][8]
                d["overs"] = match[0][5]/6
                d["given"] = match[0][7]
                _list.append(d)
            Team_Final_Score = 0
            for i in _list:
                Total_Points = self.points_function(i)
                self.listWidget_2.addItem(str(Total_Points))
                Team_Final_Score += Total_Points
            self.lineEdit.setText(str(Team_Final_Score))
            msg = QMessageBox()
            msg.setWindowTitle("Team Final Points")
            msg.setText("Your Team Points:  "+ str(Team_Final_Score))
            msg.setIcon(QMessageBox.Information)
            msg.setStandardButtons(QMessageBox.Ok)
            x = msg.exec_()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Warning Message")
            msg.setText("Please select Team and Match")
            msg.setIcon(QMessageBox.Warning)
            msg.setStandardButtons(QMessageBox.Cancel|QMessageBox.Retry|QMessageBox.Ignore)
            msg.setDefaultButton(QMessageBox.Retry)
            x = msg.exec_()
            



    def MatchTables(self, match, player):
        c = Cricket.cursor()
        if match == "Match1":
            player_stat = "SELECT * from Match1 WHERE Player='"+player+"';"
            c.execute(player_stat)
            s = c.fetchall()
            return s
        elif match == "Match2":
            player_stat = "SELECT * from Match2 WHERE Player='"+player+"';"
            c.execute(player_stat)
            s = c.fetchall()
            return s
        elif match == "Match3":
            player_stat = "SELECT * from Match3 WHERE Player='"+player+"';"
            c.execute(player_stat)
            s = c.fetchall()
            return s
        elif match == "Match4":
            player_stat = "SELECT * from Match4 WHERE Player='"+player+"';"
            c.execute(player_stat)
            s = c.fetchall()
            return s
        elif match == "Match5":
            player_stat = "SELECT * from Match5 WHERE Player='"+player+"';"
            c.execute(player_stat)
            s = c.fetchall()
            return s

    def points_function(self, dict):
        runs,balls_faced,fours,sixes  = dict.get("runs"), dict.get("balls"), dict.get("4"), dict.get("6")
        try:
            strike_rate = int((runs / balls_faced) * 100)
        except:
            strike_rate = 0
        batting_points = 0
        batting_points += runs // 2
        if runs >= 50:
            batting_points += 5
        if runs >= 100:
            batting_points += 10
        if strike_rate in range(80, 101):
            batting_points += 2
        if strike_rate > 100:
            batting_points += 4
        if fours > 0:
            batting_points += fours * 1
        if sixes > 0:
            batting_points += sixes * 2
        wickets_taken,overs_bowled,runs_given = dict.get("wkts"),dict.get("overs"),dict.get("given")
        try:
            economy_rate = runs_given // int(overs_bowled)
        except:
            economy_rate = 0
        bowling_points = 0
        bowling_points += wickets_taken * 10
        if wickets_taken == 3:
            bowling_points += 5
        if wickets_taken >= 5:
            bowling_points += 10
        if 3.5 < economy_rate < 4.5:
            bowling_points += 4
        elif 2 < economy_rate < 3.5:
            bowling_points += 7
        elif economy_rate < 2:
            bowling_points += 10
        no_of_fields = dict.get("field")
        fielding_points = 0
        fielding_points += no_of_fields * 10
        final = batting_points + bowling_points + fielding_points
        return final

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
